  
version: '3'
services:
  server:
    image: node:12.18.4
    working_dir: /code
    ports: 
      - 3000:3000
      - 80:8080
    environment: 
      - DB_NAME=notes
      - DB_CONNECTION=mongodb://dockerdb:passwd@db:27017
    depends_on:
      - db
    
    volumes:
      - type: bind
        source: ./
        target: /code
    command: bash -c "npm install && npm run dev"

  db:
    image: mongo:4-focal #I can only run mongo below v5 
    # to access this container in interactive mode type: docker exec -it fp_majanotes_db_1 mongo --username dockerdb
    # when prompted the password is defined below (passwd) 
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=dockerdb
      - MONGO_INITDB_DATABASE=notes
      - MONGO_INITDB_ROOT_PASSWORD=passwd
volumes:
  dbdata:
